### ISSUE TITLE
Location lost in translation

### ISSUE THREAD

**Issue by vandres** [ethercreative/simplemap#149] opened 2019-03-30 05:19 UTC
### Description
I have your map in a section. It is set to "not translatable". When I add a location and save it in the base language, the location in the other locales is empty.

### Steps to reproduce

1. add a locale e.g. "fr"
2. add a map in an entry in the base language and save it
3. location in locale "fr" is empty

### Additional info

- Craft version: 3.1.x
- SimpleMap version: latest
- PHP version: 7.2
- Database driver & version: -
- Other Plugins: -

**Comment by Tam** [comment] 2019-04-01 14:04
Closing this, dupe of #141.

**Closed as completed by Tam** 2019-04-01 14:04 UTC
