### ISSUE TITLE
Pagination gives error - Not unique table/alias: 'simplemap' 

### ISSUE THREAD

**Issue by bighoho123** [ethercreative/simplemap#81] opened 2018-01-25 01:27 UTC
### Description

When you create an elementCriteria and paginate with the following code it throws 

`Not unique table/alias: 'simplemap'`

```twig
{% paginate craft.entries.simpleMap({
        location: { 'lat': -34.928, 'lng': 138.6 },
        country: 'AU',
        radius: 100,
        unit: 'mi'
    }).limit(10) as pageInfo, pageEntries %}
```

### Steps to reproduce

1. Create an elementCriteria with SimpleMap criteria
2. Paginate it in the twig template

### Additional info

I will create a pull request for the fix shortly.

**Comment by lukeyouell** [comment] 2018-01-25 09:51
@bighoho123 check out [#70](https://github.com/ethercreative/simplemap/issues/70) for a possible fix

**Comment by Tam** [comment] 2018-01-25 11:57
Closing this since it's a duplicate of #70

**Closed as completed by Tam** 2018-01-25 11:57 UTC
