### ISSUE TITLE
Call to a member function getMap() on null

### ISSUE THREAD

**Issue by lukeyouell** [ethercreative/simplemap#84] opened 2018-01-26 10:02 UTC
### Description

`Call to a member function getMap() on null` error displayed when saving new map field, this error is then displayed when trying to access any page in the CP and is only resolved by deleting the field from the DB.

### Steps to reproduce

1. Fresh Craft installation
2. Create location field (my parameters pictured below)
3. Save field

<img width="754" alt="image" src="https://user-images.githubusercontent.com/24975058/35434720-ff84b14a-027f-11e8-96c3-61f02ce20678.png">

### Additional info

- Craft version: 3.0.0-RC7.1
- SimpleMap version: 3.2.0
- PHP version: 7.2.1
- Database driver & version: MySQL

**Comment by lukeyouell** [comment] 2018-01-26 10:04
Error page pictured below

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/24975058/35434779-3e48a3a0-0280-11e8-91ae-43c45e4bc675.png">

**Comment by Tam** [comment] 2018-01-26 10:43
This look likes a duplicate of #61, the cause of which was the amcommand plugin (am-impact/amcommand#33). What other plugins do you have installed (I can't replicate it using a fresh install with no other plugins)?

**Comment by lukeyouell** [comment] 2018-01-26 10:45
@Tam I have the following plugins installed

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/24975058/35436357-fe6a23d4-0285-11e8-9269-1766ad56973c.png">

**Comment by lukeyouell** [comment] 2018-01-26 10:48
@Tam I created a map field after disabling 'XML Sitemap', which lead to no error being thrown...

**Comment by lukeyouell** [comment] 2018-01-26 11:05
If I install 'XML Sitemap' *after* creating the field, everything is fine.

**Comment by Tam** [comment] 2018-01-26 11:22
I've submitted a pull request to the XML Sitemap repo which should fix the issue, and mean you don't need to mess about with the load order of the plugins to prevent the error!

**Comment by lukeyouell** [comment] 2018-01-26 11:24
Cheers @Tam - love the plugin!

**Closed as completed** 2018-01-29 11:08 UTC
